# Generated by Django 3.2.19 on 2023-05-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0005_auto_20230519_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='fee',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
