# Generated by Django 3.2.19 on 2023-05-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduhub', '0006_alter_course_details_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='active_status',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course_details',
            name='calttag',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='instalttag',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='placements',
            name='plaalttag',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testalttag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
